"""Generate daily markdown news reports."""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from .config import AgentConfig, DEFAULT_CONFIG
from .models import NewsArticle


CATEGORY_LABELS = {
    "industry": "Industry & Product News",
    "research": "Research & Analysis",
    "search": "Trending Topics",
    "community": "Community & Developer",
    "general": "General",
}


def _group_by_category(articles: list[NewsArticle]) -> dict[str, list[NewsArticle]]:
    grouped: dict[str, list[NewsArticle]] = defaultdict(list)
    for article in articles:
        grouped[article.category].append(article)
    return grouped


def generate_report(
    articles: list[NewsArticle],
    config: AgentConfig = DEFAULT_CONFIG,
    report_date: datetime | None = None,
) -> str:
    now = report_date or datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M UTC")

    lines = [
        f"# Agentic AI Daily News Report",
        "",
        f"**Date:** {date_str}  ",
        f"**Generated:** {time_str}  ",
        f"**Articles found:** {len(articles)}",
        "",
        "> Automated daily briefing on agentic AI — autonomous agents, multi-agent systems,",
        "> agent frameworks, and the latest industry developments.",
        "",
    ]

    if not articles:
        lines.extend([
            "## No matching articles today",
            "",
            "No agentic AI news matched the configured keywords in the lookback window.",
            "Try running again later or widening the lookback period with `--lookback-hours`.",
            "",
        ])
        return "\n".join(lines)

    lines.extend([
        "## Executive Summary",
        "",
    ])

    top = articles[:5]
    for i, article in enumerate(top, start=1):
        lines.append(f"{i}. **{article.title}** — *{article.source}*")

    lines.append("")
    lines.append("---")
    lines.append("")

    grouped = _group_by_category(articles)
    category_order = ["industry", "research", "search", "community", "general"]

    for category in category_order:
        cat_articles = grouped.get(category, [])
        if not cat_articles:
            continue

        label = CATEGORY_LABELS.get(category, category.title())
        lines.extend([f"## {label}", ""])

        for article in cat_articles:
            lines.append(f"### {article.title}")
            lines.append("")
            lines.append(f"- **Source:** {article.source}")
            lines.append(f"- **Published:** {article.published_display}")
            lines.append(f"- **Link:** {article.url}")
            if article.matched_keywords:
                keywords = ", ".join(f"`{k}`" for k in article.matched_keywords[:5])
                lines.append(f"- **Matched:** {keywords}")
            if article.summary:
                lines.append(f"- **Summary:** {article.summary}")
            lines.append("")

    lines.extend([
        "---",
        "",
        "*Report generated by [Agentic AI News Agent](https://github.com/PW0916/Lab).*",
        "",
    ])

    return "\n".join(lines)


def save_report(
    content: str,
    config: AgentConfig = DEFAULT_CONFIG,
    report_date: datetime | None = None,
) -> Path:
    now = report_date or datetime.now(timezone.utc)
    report_dir = Path(config.report_dir)
    report_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{now.strftime('%Y-%m-%d')}.md"
    path = report_dir / filename
    path.write_text(content, encoding="utf-8")
    return path
